general {
    lock_cmd = ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = ~/.config/hypr/scripts/lock.sh --after-sleep
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5 min: lock
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600 # 10 min: screen off
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 900 # 15 min: suspend
    on-timeout = systemctl suspend || loginctl suspend
}
